require 'attribute'
require 'set_attributes'
require 'initializer'
require 'validate'
require 'virtual'

require 'schema/schema'
require 'schema/schema/assertions'
require 'schema/schema/compare/difference'
require 'schema/schema/compare/difference/attributes'
require 'schema/schema/compare'
require 'schema/schema/attribute'
require 'schema/data_structure'
require 'schema/validation/nil_attributes'
require 'schema/validation/error'
